### ISSUE TITLE
Feature request: Restriction by ANY course completion

### ISSUE THREAD

**Issue by adigitalife** [ewallah/moodle-availability_coursecompleted#1]
First of all, great plugin!  It's absolutely essential to my Moodle site.  One request though.  Would it be possible to set the restriction to ANY course?

**Comment by ewallah** [comment]
I do not think this feature is absolutely necessary because one can base the completion of a course on the 'Completion of other courses'.

So if you configure your course completion on the fact that ANY of the other courses completes the course, this will happen: a user completes another course -> a user completes this course -> the module becomes available (or hidden).

**Comment by adigitalife** [comment]
Actually, this is the use case:
- Course A is the training
- Course B is the certification. It contains an exam and certificate download.
- We would like to restrict access to the exam until Course A is complete.
- To complete Course B, you must complete Course A **and** pass the exam of Course B
- Certificate download is restricted until Course B is complete

So, we use your plugin to restrict access to the certificate download in Course B.  However, we have no way to restrict access to the exam in Course B.  If we use course completion to restrict access to the exam, then we can't include the exam itself in Course B completion.  This means you can complete Course B by simply completing Course A without taking the exam in Course B.  This then causes problems for Course C.

By the way, we also can't simply move the certificate to Course A because there's multiple versions of it.  In other words, to qualify for certification (Course B), you can complete Course A.1 or A.2, etc.  So regardless of which version of Course A you complete, the certification is centralized in Course B.

**Comment by ewallah** [comment]
I do see your problem but this new feature would complicate and slow down things. The current plugin only depends on the completion of this course, the new feature would depend on other courses. The documenting also would become a nightmare, putting me in a situation where I have to explain again and again the different perspective.

Best practice here would be to develop a new access restriction plugin, ignoring completion of the current course and optimized to function also in an environment with 2000+ courses. Perhaps the idea of crowdfunding can be interesting?

But in your specific situation, I think adding a core\event\course_completed event to your theme to enrol users in course B would be a better solution.

**Comment by adigitalife** [comment]
Thanks for the comments and advice.  I'll look into this.

**Comment by ewallah** [comment]
Perhaps the enrolment on coursecompletion (https://github.com/ewallah/moodle-enrol_coursecompleted) can fix your problems?
Warning, still in beta!
