### ISSUE TITLE
{$a} functionalities in some strings

### ISSUE THREAD

**Issue by jrojas-garrido** [ewallah/moodle-availability_coursecompleted#2]
Hello, this is a request for an improvement,

Due to the time it takes to register the completion of the training, caused by the frequency of execution of the Cron task, it is important for the user to know what to expect in order to access the activity.

Could you add the variables to these strings ( requires_notcompleted , requires_completed ,  getdescriptionnot , getdescription ) in order to get this type of message.

Example :

requires_notcompleted = You have not completed this course. This '{$a}' will be available once you have completed the course.

and replace the variable for the activity type to get these results:

You have completed this course. This SCORM will be available once you have completed the course.
You have completed this course. This Attestation will be available once you have completed the course.
You have completed this course. This File will be available once you have completed the course.

Thank you.

**Comment by iplusacademy** [comment]
Hello Jose,

THX for the suggestion, but when I implement your changes, I will not follow the default wording in Moodle:  As far as I know, I do not see activity types in availability_grade, availability_date or any other availability restrictions.

Mostly, we mix different restrictions in a course, so changing the wording in one condition could be confusing, especialy when you combine conditions:  Not available unless: grade > 80 OR coursecompleted = true. Do you have an idea how your changes would look in complex AND OR situations?  

Another issue is to implement the changes in different languages.  I have an idea that the current implementation works best in most languages. Negation and combination in a language is not always done the English or Spanish way, so the solution should also work in Japanese and Suomi.

It could be a good idea to start a new discussion in the Moodle fora to see if there are others interrested in such a change. I will also try to get some feedback from the teachers I work with. 

But on first sight I think the changes would be better done in Moodle core: Not available unless => This File wiill be available unless.

Greetings,
R
