### ISSUE TITLE
Not able to see the "Course Completed" restriction anywhere

### ISSUE THREAD

**Issue by jshrek** [ewallah/moodle-availability_coursecompleted#3]
I have created a couple classes for testing out this plugin.

Plugin is installed and visible.

In Class 2 I have set the course completion requirements, and under Admin > Course Admin > Reports  I can see the Course Completion report, so I know that this is set properly.

When I go to another classs, Class 3, and I go into either Edit Section (top section of the course) or into Edit Settings for first activity of the course, I am not seeing any option for Restrict by Course Completion under the Restrict Access sections.

Am I mis-understanding the use of this plugin?

I am trying to prevent access to a course, until the previous course has been completed.

Thanks

**Comment by ewallah** [comment]
This plugin limits access to modules if THIS course is completed or not.

If you want to restrict access based on previous courses, you need to use the 'Restriction by other course completion'.
