### ISSUE TITLE
Improve integration with Moodle Workplace Certificates

### ISSUE THREAD

**Issue by carlicockrell** [ewallah/moodle-availability_coursecompleted#4]
The US Learning Design team has uncovered something that may be improved upon. We understand your team may not be able to address this, but wanted to make you aware of the situation in case you have insight into why this may be occurring.

Story: When using the activity level certificate with the dynamic field of course completion date, we often had instances where users were accessing the certificate prior to the cron running, and the certificate had a blank field for the course completion date. Because of this issue, we started pairing activity level certificates with plugins/availability_coursecompleted.

Issue: This design does not appear to work properly with uploading course completion dates via CSVs. We have experienced issues where the certificate never fires if we are using Course Completed = Yes as the access restriction. This could be because uploading a CSV with coursecompleted1 does not work to fire the certificate because the date of completion is not the only thing that factored into whether Course Completed = Yes is actually "met."

Consideration: This is isolated specifically to the activity level certificate. If we are triggering the certificate based upon course completion with a dynamic rule, overring the coursecompleted1 date works fine. 

Steps to replicate:

Install plugins/availability_coursecompleted on a site
Create a certificate activity in a course
Set access restriction to Course Completed = Yes
Set course completion to whatever you'd like to use
Enable automatic sending of the certificate
Upload a spreadsheet overriding course completion date
Note that the certificate never triggers
Steps to compare to "normal" functionality:

Create a certificate activity in a course
Set access restriction to something like User Profile Field that matches your test user in the spreadsheet you will upload
Set course completion to whatever you'd like to use
Enable automatic sending of the certificate
Upload a spreadsheet overriding course completion date
Note the certificate does issue

This was tested on the latest 4.1 but is likely an issue across all versions.

**Comment by ewallah** [comment]
THX for the information.

This plugin only uses the Moodle API to check that a course is completed or not. I do not have access to the Moodle Workplace API to see what was changed or what is triggering the issue of a certificate. The origin of this problem could be related to [3 lines](https://github.com/ewallah/moodle-availability_coursecompleted/blob/main/classes/condition.php#L98-L100):

- the use of the global $USER->id vs $userid (needed for reports)?
- changes in the \completion_info($course)->is_course_complete() function?

**Comment by marinaglancy** [comment]
Hello! Carli reported the same issue in the certificate tracker too https://tracker.moodle.org/browse/WPOS-48
https://moodle.org/plugins/tool_certificate and https://moodle.org/plugins/mod_coursecertificate are open-source plugins.

I can only reply the same - we only use core Moodle API to get the list of users to email certificates to, see mod/coursecertificate/classes/helper.php :

        // Filter only users with access to the activity {@see info_module::filter_user_list}.
        $info = new \core_availability\info_module($cm);
        $filteredusers = $info->filter_user_list($potentialusers);

**Comment by marinaglancy** [comment]
it looks like this plugin has to implement methods:

    is_applied_to_user_lists() 
    filter_user_list()

Other places in core where filter_user_list() is used and that will not work here:
- browsing list of forum subscribers: create a forum with automatic subscription and add an availability condition of course completion. Browse the list of forum subscribers - it should only list people who actually completed course.
- mod_feedback list of users who have not completed feedback
- mod_assign , function list_participants() - I think this is used in the assignment grading
- I can see something also in mod_quiz and mod_lesson but I think these examples are already enough

**Comment by ewallah** [comment]
THX @marinaglancy for your report.

If this filter_user_list is used in so many places, I wonder why the is_applied_to_user_lists function defaults to false.

Let's start testing to see if [the changes](https://github.com/ewallah/moodle-availability_coursecompleted/blob/ewallah-issue-4/classes/condition.php#L161) are fixing the problem.

@carlicockrell, can you provide a Behat scenario to see if my changes are working?

**Comment by marinaglancy** [comment]
Thank you @ewallah , this is exactly what I meant. 
But I also realised that we use the "filter_list" function to pre-filter the list of users and for each user we still check
{code}
info_module::is_user_visible($cm, $filtereduser->id, false)
{code} 

So even though this will be a great improvement for this plugin it might not have solved Carli's problem.

I looked at your existing code and I can't see what could have caused the problem for Carli

@carlicockrell , after you upload this CSV, if you go to the "Course completion" report, do you see all users as completed there?

**Comment by carlicockrell** [comment]
@marinaglancy and @ewallah - Yes, once the users are enrolled in the course (even if you did the coursecompleted1 CSV override BEFORE enrolling), the Course Completion report in the course level has them checked off, as does the Course report from the data store in Custom Reports. I just tested this again, and with the plugin added to the certificate activity, I could not get the certificate to issue from the activity level certificate. However, it fires just fine with dynamic rule. It makes me wonder if Course completion source for this plugin is different than what is looked for with course completion in, for example, dynamic rules.

Also, I may not be the right person to provide a behat scenario as I'm not on the developer side of things. Let me provide an explanation that may help:

As an admin or course designer, I want the activity "Certificate" in Moodle to issue a certificate when using the moodle-availability_coursecompleted plugin regardless of how the course is completed (manually overriding the course completion date, for example).

**Comment by ewallah** [comment]
This plugin does not support dynamic rules.

For this a class named classes/tool_dynamicrule/condition/??? is needed. But the documentation for this class is not public, nor can I test this class (it is propriety software).

**Comment by carlicockrell** [comment]
@ewallah I'm sorry for the confusion. I didn't mean that your plugin should support dynamic rules. I was meaning that if @marinaglancy looks at the difference between how dynamic rules are treating the course completion trigger and this plugin, that might be a clue.

**Comment by ewallah** [comment]
When you use bulk upload or manually update course completion, you have to fire the course_completed event so this plugin can pick up this event and restrict or make available.
